### ISSUE TITLE
Assets are always requested from server

### ISSUE THREAD

**Issue by easga** [NekR/offline-plugin#200] opened 2017-03-08 15:29 UTC
Hello,
This could rather be a newbie question who could not get the plugin to work and feeling helpless after so many attempts playing with the configurations. Please assist me on where to ask those type of questions.

We have a secure index.html which loads our assets at folder /assets/ which is public. Plugin specifies assets/sw.js as output path. 
When i load page on Chrome, i can see that service worker is initialised successfully and all assets appear to be in application cache. Whenever i reload the page, i see that they are still loaded from network all the time.  Then i open the cached assets in a new tab, and when i reload the tab, i see that they are loaded from Service Worker. When i do hard reload, they do come from network, and normal reload they are loaded from Service Worker. The only difference i see between those requests are the headers. But i do not get what i shall do make it work.

For example for the url : 
https://manager.adtech-union.tv/automated-guaranteed/assets/application.38610c98a6769d34d87d.js
When i reload this:
<img width="1280" alt="screen shot 2017-03-08 at 16 18 56" src="https://cloud.githubusercontent.com/assets/1662107/23709874/2310d30a-041b-11e7-9d7d-340148264bf3.png">
When i hard reload it:
<img width="1266" alt="screen shot 2017-03-08 at 16 21 16" src="https://cloud.githubusercontent.com/assets/1662107/23709931/521e3ec6-041b-11e7-862c-af35bb0e0129.png">

(When i am logged in, cookies are sent too.)

When index.html requests for those assets, it always sends the same headers as hard reload, so it creates the same result of loading from network. 

This is how application cache looks like.
<img width="904" alt="screen shot 2017-03-08 at 16 26 55" src="https://cloud.githubusercontent.com/assets/1662107/23710192/207d01b2-041c-11e7-9a35-236757db079e.png">

The service worker is here: 
https://manager.adtech-union.tv/automated-guaranteed/assets/sw.js

It feels like i am missing a very basic knowledge here, might be related to how our servers are configured or some axios request interceptors but i tried it with external scripts, they always get loaded from network too.

**Comment by NekR** [comment] 2017-03-08 15:42
Hard Reload bypassed ServiceWorker completely, that's it's Hard Reload after all. You may also want to read [this doc](https://github.com/NekR/offline-plugin/blob/master/docs/updates.md). It's about SW update process, but there could be some details which may help you.

**Comment by easga** [comment] 2017-03-08 16:55
I gave hard reload example to emphasize that the requests are also always having same headers and always bypassing service workers when the initiator is index.html in case of **normal reload**. So is bypassing related to certain headers being present in one of those requests?

**Comment by NekR** [comment] 2017-03-08 17:24
@easga sorry, I don't get what you mean here. On one screenshot it's loaded from ServiceWorker (it's marked as `(from ServiceWorker)`) and on second one which is with "Hard Reload" it loaded from the network. What the problem with it?

**Comment by easga** [comment] 2017-03-08 17:34
Sorry, i think i fail to explain it. So this loading from service worker happens only When i type the full asset URL in the bar. However though, in reality they are loaded by index.html Which lies in root and those files are under assets. There, they are never loaded from service workers and request headers look like the screenshot ( as if i hard reload the asset itself in a seperate tab)

**Comment by GGAlanSmithee** [comment] 2017-03-08 17:55
@easga can you share your webpack config please?

**Comment by NekR** [comment] 2017-03-08 18:37
Well, headers are unrelated for sure. I'm also sure it works as it should because are still cached and returned from cache when they are requested directly. Most likely problem is in understanding what's going on.

@easga how do you detect if request went through cache or not apart from looking at headers?

**Comment by NekR** [comment] 2017-03-08 18:43
Also, if ServiceWorker file is on `/assets/sw.js` path, you cannot cache `/` path.

**Comment by easga** [comment] 2017-03-08 18:53
@GGAlanSmithee i will provide the full webpack config tomorrow at office, now i dont have access to code. I started with really basic offline plugin setup, and tested some prefetchRequest(ServiceWorker) settings to see if it helps but it does not, and they are public anyways. I was suspicious about a library (company' s own) which has Axios request interceptors which i guess intercepts pretty much any request to add tokens, but i guess it is not relevant because i loaded the asset directly with URL when i am logged out too. Works just fine. Same webpack config on a dummy pretty much empty project to just test this works fine too. 

@NekR I am just looking at status 200 (from Service Worker) for the cached assets, which never appears when i load the app. Load times are also more than 100ms which tells me that they are not really from service workers. I do not cache index.html and i do not want it to be cached either. It templates a few things on server depending on users. So, i have index.html which has **base** href set to 'automated-guaranteed' and assets is the public folder on the server which has everything. sw.js, css, js, /fonts, /images.. When i look at the absolute paths, they seem all alright and yeah they work as intended when loaded directly.

**Comment by NekR** [comment] 2017-03-08 19:08
@easga hmm.. sounds weird. `<base>` might be the cause though. If all assets are in `/assets`, can you try to set `new OfflinePlugin({ publicPath: '/assets/' })` option and check if it helps?

**Comment by NekR** [comment] 2017-03-08 19:08
When you will be in the office, of course.

**Comment by easga** [comment] 2017-03-08 19:15
I think i might have tried that. Dont you think /assets/ will try to load it from root? like https://manager.adtech-union.tv/assets/ ?  My webpack publicPath is empty string, and since sw.js output is 'assets/sw.js', plugin writes all the paths as '../assets/application.css' etc. I first was attempting the plugin without manipulating output, so it would end up at the same place as index.html but then i  thought it would easier to setup if everything is under public folder including sw.js.

**Comment by NekR** [comment] 2017-03-08 19:27
> Dont you think /assets/ will try to load it from root?

That's what I said. If your assets are in `/assets/` then set to `/assets/`, if on other path then set other path.

Okay, I know what's going on:

> Without foreign fetch Service Workers can only intercept fetches for resources when the fetch originates on a page that is controlled by the service worker
> -- https://github.com/w3c/ServiceWorker/blob/master/foreign_fetch_explainer.md

In your case `/` isn't controlled by SW because SW is on `/assets/sw.js` path and hence its scope is `/assets/`. 

You shouldn't really cache `/` to make it work, you just have to have correct scope for SW.

**Comment by easga** [comment] 2017-03-08 19:49
@NekR my assets are under https://manager.adtech-union.tv/automated-guaranteed/assets/ , not  https://manager.adtech-union.tv/assets/. So there are many other apps under same host, where mine runs on /automated-guaranteed/ as specified in base href. So SW shall have the root scope even though everything is under /assets/ ? Or is it controlling '/' but i shall specify public path so it controls '/assets' ? Sorry if i get it all wrong  :)

**Comment by easga** [comment] 2017-03-08 19:55
I guess i got it. Index.html is in root so SW does not control the requests originating from that. So one solution is to move sw.js to root and request it with tokens, so it controls the requests. Do you suggest any other way if i keep sw.js as is?

**Comment by easga** [comment] 2017-03-08 20:12
Thanks! Thanks!
http://stackoverflow.com/questions/35358038/how-to-register-a-service-workers-scope-one-directory-above-where-the-service-w

**Comment by NekR** [comment] 2017-03-08 20:26
Yeah, you can change the scope manually by setting an option for it, but I find it more tedious than just moving the file. Anyway, whatever works for you :-)

**Closed by NekR** 2017-03-08 20:26 UTC

**Comment by easga** [comment] 2017-03-08 20:32
Great job with the plugin! And can not thank you enough with your help! It made my day!

**Comment by NekR** [comment] 2017-03-08 20:36
Thanks. Sure, you are welcome 👌

**Comment by GGAlanSmithee** [comment] 2017-03-08 20:54
For future reference, @NekR is reffering to the `scope` of the `ServiceWorker` option, as mentioned in the docs [here](https://github.com/NekR/offline-plugin/blob/master/docs/options.md#serviceworker-object--null--false). @NekR let me know if you'd like to mention something about this in the FAQ and I'd be happy to send a PR.

**Comment by NekR** [comment] 2017-03-08 21:22
@GGAlanSmithee yeah, thank you for extended info :-) Do you have any ideas on how to better describe this in the FAQ? Because I don't at the moment, a bit overwhelmed with other things. Feel free to do the PR if you can describe that 💪
