### ISSUE TITLE
making react ssr app work offline

### ISSUE THREAD

**Issue by simran-k** [NekR/offline-plugin#215] opened 2017-03-23 12:46 UTC
I am using https://github.com/erikras/react-redux-universal-hot-example boilerplate for my react-app that uses server side rendering.

My question is how do I make it work offline?

All of the project links that are listed as using offline-plugin, none of those really load when I go offline. 

The browser just says there is no internet connection. For ex: https://phenomic.io/ .

Is that not what it is supposed to do?

Also, how do I know if my resources are being loaded from CacheStorage. I see disk cache and memory cache in my network calls but those are there even if I am not using offline plugin. How do I know that the caching is actually working, being loaded from Cache Storage and network calls are not going through.

Also, For the app-shell, I do not have index.html or any html for that matter. As you can see in the boilerplate, is has Html.js inside of helpers folder and that is what generated the page and injects the route through server side rendering.

I see service worker enabled in my project and I see webpack resources listed in cache storages but my page does not load when offline. How do I fix this?

My code and project follow exactlly the same structure as in the boilerplate.

**Comment by GGAlanSmithee** [comment] 2017-03-23 12:56
@simran-k loading https://phenomic.io/ in offline mode after first having it cached shows the resources being loaded from the service worker like it's supposed to - is this not what you are seeing?

![image](https://cloud.githubusercontent.com/assets/11805103/24248590/59b9984a-0fd0-11e7-87f0-59b3de29712c.png)

**Comment by simran-k** [comment] 2017-03-23 13:05
@GGAlanSmithee : That is not what I see at all for phenomic.io. I am on Chrome and ubuntu system.

when online but after caching of assets:
![phenomic](https://cloud.githubusercontent.com/assets/17847555/24248916/5ff51000-0ff7-11e7-840e-5af3921dbe7e.png)

when offline
![phenomic2](https://cloud.githubusercontent.com/assets/17847555/24248937/70c5b182-0ff7-11e7-9b59-4ae5136a506c.png)

My website is running on localhost and http but even the websites listed are not working offline for me as mentioned

**Comment by GGAlanSmithee** [comment] 2017-03-23 13:14
What can you see regarding phenomic.io if you go to chrome://serviceworker-internals/ ?

![image](https://cloud.githubusercontent.com/assets/11805103/24249280/eeecd448-0fd2-11e7-802e-f1e497b68708.png)

**Comment by simran-k** [comment] 2017-03-23 13:19
This is what I see:

![internals](https://cloud.githubusercontent.com/assets/17847555/24249496/80827a7c-0ff9-11e7-9b1c-cdd765d509f5.png)

**Comment by GGAlanSmithee** [comment] 2017-03-23 13:28
I can see our version id differs quite a lot, just to make sure there is no ghost haunting, try closing all phenomic tabs, delete the phenomic sw from chrome://serviceworker-internals/ and then reload phenomic.io first normally, then without internet connection

**Comment by simran-k** [comment] 2017-03-23 13:43
@GGAlanSmithee : Hey, What exactly is a version id and what it exactly does? Turns out the page does not display if I have my console open.loads if not. So, I was always using offline checkbox from console tool and it always failed that way. If I turn my internet off, it works. But I am never really able to see "from service worker" as you do in your snapshot. Would you know why is this happening and what can I do to solve this?

**Comment by GGAlanSmithee** [comment] 2017-03-23 13:50
@simran-k Sorry for the confusion, the version id is unrelated. 

Using the offline tick works, and should work:

Please try doing exactly this:

1. Close any tab with phenomic.io
2. Remove current service worker from chrome://serviceworker-internals/
3. Open phenomic.io in a new tab
4. Close the tab
5. Open phenomic.io in a new tab
6. Reload the tab with network throttling = offline

Does this work as expected?

**Comment by NekR** [comment] 2017-03-23 14:34
> All of the project links that are listed as using offline-plugin, none of those really load when I go offline.

Interesting. What's none really load?

> The browser just says there is no internet connection. For ex: https://phenomic.io/ .

It works for me just fine.

> That is not what I see at all for phenomic.io. I am on Chrome and ubuntu system.
> My website is running on localhost and http but even the websites listed are not working offline for me as mentioned. Also, yes, SW installed properly and is running

We cannot help you because something wrong is with your browser.

> So, I was always using offline checkbox from console tool and it always failed that way. If I turn my internet off, it works. But I am never really able to see "from service worker" as you do in your snapshot. Would you know why is this happening and what can I do to solve this?

Something wrong with your browser. Try Firefox maybe. Reinstall Chrome. Or maybe even tell us your Chrome version. Anyway, closing now. Feel free to chat here though. 

@GGAlanSmithee thanks for handling this! 👌

**Closed by NekR** 2017-03-23 14:34 UTC

**Comment by NekR** [comment] 2017-03-23 14:36
Oh, why I'm closing this: Your browser isn't working properly so we won't be able to figure out what's its issue or `offline-plugin`'s. Once your browser works properly and basic websites which are offline-capable start working, then we can open another issue and try to figure out `offline-plugin`'s issues, if any.

**Comment by primozs** [comment] 2017-03-23 15:11
Hi,
I have a similar Issue:
Service workers seams to be registered but on offline does not work. What could be the issue?
Maybe the "/" http://localhost:8888/ instead of http://localhost:8888

Screenshots
<img width="786" alt="screen shot 2017-03-23 at 16 09 12" src="https://cloud.githubusercontent.com/assets/1006789/24254407/1fda3504-0fe3-11e7-91ad-413123190f12.png">
<img width="580" alt="screen shot 2017-03-23 at 16 08 45" src="https://cloud.githubusercontent.com/assets/1006789/24254406/1fda0304-0fe3-11e7-9691-9e588a887cd6.png">
<img width="592" alt="screen shot 2017-03-23 at 16 08 24" src="https://cloud.githubusercontent.com/assets/1006789/24254409/1fdf0caa-0fe3-11e7-8198-7a25e65bfd70.png">
<img width="633" alt="screen shot 2017-03-23 at 16 07 41" src="https://cloud.githubusercontent.com/assets/1006789/24254408/1fddbb52-0fe3-11e7-8c39-1cc49eafaecc.png">
<img width="310" alt="screen shot 2017-03-23 at 16 07 19" src="https://cloud.githubusercontent.com/assets/1006789/24254405/1fd853f6-0fe3-11e7-98da-6cd0ee749f1b.png">

**Comment by NekR** [comment] 2017-03-23 15:29
@primozs I don't remember actually. I saw such behavior couple of times, but cannot remember what went wrong. Is this happening only for your website or with all websites which use ServiceWorker (e.g. same as the author of this issue have)?

**Comment by primozs** [comment] 2017-03-23 15:40
Hi, @NekR 
https://phenomic.io/ works for me and there I actually noticed that when I set offline service worker list stays the same in DevTools. I don't think "/" is the problem since service workers from others also have it.

My webpack config is:
Result is the same without this custom settings
```
new OfflinePlugin({
      publicPath: '/',
      ServiceWorker: {
        publicPath: '/sw.js',
        events: true
      },
      AppCache: {
        events: true
      }
    })
```

Runtime I have like this:
Screenshots were made with NODE_ENV=production SERVER=dev pm2 start build/dist/server/start.js
```
// This code is being run only on the client. Could this be the issue?
if (process.env.NODE_ENV === 'production') {
  const OfflinePlugin = require('offline-plugin/runtime');

  OfflinePlugin.install({
    onInstalled: function() {
      store.dispatch({ type: 'SW_INSTALLED'});
    },

    onUpdateReady: function() {
      OfflinePlugin.applyUpdate();
    },

    onUpdated: function() {
      window.location.reload();
    }
  });
}
```

**Comment by primozs** [comment] 2017-03-23 21:24
my final webpack config is
```
new OfflinePlugin({
      safeToUseOptionalCaches: true,
      externals: [
        'apple-touch-icon.png',
        'favicon-32x32.png',
        'favicon-16x16.png',
        'favicon.png',
        'safari-pinned-tab.svg',
        '*.ttf'
      ],
      publicPath: '/',
      caches: {
        main: [
          'app.*.css',
          'vendor.*.js',
          'app.*.js',
        ],
        additional: [
          ':externals:'
        ],
        optional: [
          ':rest:'
        ]
      },

      ServiceWorker: {
        publicPath: '/sw.js',
        events: true
      },
      AppCache: {
        events: true
      }
    })
```
I have deployed the app to http domain and for a while it was working offline. Now its not.
It seams It works a bit random. https://pisarna.naviter.com:8080/

**Comment by NekR** [comment] 2017-03-23 21:24
@primozs if you will have a repro I'll be able to help you / debug the code. Or you meant that you are using phenomic? I recently built a fully SSR phenomic app with `offline-plugin` and everything was just fine.

**Comment by NekR** [comment] 2017-03-23 21:26
@primozs okay, so you just posted a link, I wanted to say that I missed the comment and you deleted it. Turns out you posted it in a minute before my comment.

So.. what we are going to do with this?

**Comment by primozs** [comment] 2017-03-23 21:26
@NekR Hi I dont have public repo but this is currently publicly debuggable https://pisarna.naviter.com:8080/

**Comment by NekR** [comment] 2017-03-23 21:28
@primozs that will work just fine :-) I don't need a public repo to debug.

**Comment by primozs** [comment] 2017-03-23 21:30
@NekR :) Thx for your eyes

**Comment by NekR** [comment] 2017-03-23 21:33
Okay, so `externals` option doesn't support wildcard so ` '*.ttf'` rule fails. But you use externals only in `additional` section so it's weird that it prevents whole SW installation. Maybe that isn't the reason though.

@primozs  Can you try to remove that rule and deploy website again?

**Comment by primozs** [comment] 2017-03-23 21:34
@NekR Yes I will try! Thx

**Comment by NekR** [comment] 2017-03-23 21:44
@primozs let me know the results please. I'll need to fix it if that was the issue.

**Comment by primozs** [comment] 2017-03-23 22:02
@NekR Hey, its not working. When I made the deploy the first time it was working for a short while. Not sure but is it possible that the problem is that I don't have index.html to cache? Maybe the problem is also how react router and code splitting on routes works? Offline was working only on the   initial route. When I set routes in externals then it was making redirects to home page and routes were not accessible.

**Comment by NekR** [comment] 2017-03-23 22:07
Well, not caching any html pages is the issue. It of course cannot be accessible offline if it has no html to display.

**Comment by NekR** [comment] 2017-03-23 22:09
@GGAlanSmithee hey, if you have time, do you have any ideas about how to write clear docs about SPA/AppShell/routes and `ServiceWorker.navigateFallbackURL` option? Because I'm kind of tired figuring out issues with "no accessible on routes"..

**Comment by NekR** [comment] 2017-03-23 22:14
@primozs in your case you need something like this, assuming `/` is where your AppShell is located. If you don't have one you should create it. Otherwise you will need to specify all your routes in `externals` manually.

```js
new OfflinePlugin({
  safeToUseOptionalCaches: true,
  externals: [
    'apple-touch-icon.png',
    'favicon-32x32.png',
    'favicon-16x16.png',
    'favicon.png',
    'safari-pinned-tab.svg',
    '/'
  ],
  publicPath: '/',
  caches: {
    main: [
      '/',
      'app.*.css',
      'vendor.*.js',
      'app.*.js',
    ],
    additional: [
      ':externals:'
    ],
    optional: [
      ':rest:'
    ]
  },

  ServiceWorker: {
    publicPath: '/sw.js',
    events: true,
    navigateFallbackURL: '/'
  },
  AppCache: {
    events: true
  }
})
```

**Comment by GGAlanSmithee** [comment] 2017-03-23 22:20
@NekR 
> @GGAlanSmithee hey, if you have time, do you have any ideas about how to write clear docs about SPA/AppShell/routes and ServiceWorker.navigateFallbackURL option?

sure! I  will try to get time tomorrow to send a PR

@primozs 
> I have deployed the app to http domain and for a while it was working offline. Now its not.

just to make sure - you are using **https**, right?

**Comment by NekR** [comment] 2017-03-23 22:22
@GGAlanSmithee thank you!

Yeah, it's https, I have a link to website. SW is being installed, it just doesn't serve html when offline and I missed that html isn't being cached.

**Comment by primozs** [comment] 2017-03-23 22:24
@GGAlanSmithee Hi, Yes I am using https. I think when it was kind of working I had '/' in externals.
I will update the config like @NekR suggested. Thank you both!
Cheers
