### ISSUE TITLE
Appcache manifest is not injected into index.html

### ISSUE THREAD

**Issue by yaitskov** [NekR/offline-plugin#294] opened 2017-08-18 15:45 UTC
Hi,

I am trying to use offline plugin to use appcache.
The problem is that index.html lacks of manifest tag.

My index.html is generated out of template. though webpack is capable of injecting bundle.js.

   ```
 plugins:[
        new CleanWebpackPlugin(['dist']),
        new HtmlWebpackPlugin({
            title: 'Output Management',
            template: 'src/index.ejs'
        }),        
        new OfflinePlugin({
            ServiceWorker: false,
            
        })
    ]
```

Use versions:
 ```
  "offline-plugin": "^4.8.3",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.18.2",
    "webpack": "^3.5.5"
```

Template: 
```

<!DOCTYPE html>
<html ng-app="ajwp" lang="en">
  <head>
    <meta charset="UTF-8">
    <title><%= htmlWebpackPlugin.options.title %></title>
    <meta name="viewport" content="width=400">
  </head>
  <body>
    <div class="view-container">
      <div ng-view class="view-frame"></div>
    </div>
    <!-- comment me -->
  </body>
</html>
```

Instead injecting attribute into html tag. 
The plugin generates another html file with the manifest attribute, which is located at 
/dist/appcache/manifest.html

**Comment by NekR** [comment] 2017-08-18 17:43
That's the behaviour. Where is the problem?

**Comment by yaitskov** [comment] 2017-08-18 18:04
As far as I understood from the application cache spec. 
Every html file should have attribute manifest referring to manifest.appcache file.
Could you explain how an html file in a sub folder with set attribute could active the appcache in my index.html?

**Comment by NekR** [comment] 2017-08-18 19:30
I'm not going to, sorry. There are plenty of information about it over the internet. But I'm going to tell you that works and it works the way intended too. Otherwise it won't be implemented that way.

**Closed by NekR** 2017-08-18 19:30 UTC

**Comment by yaitskov** [comment] 2017-08-18 19:49
https://www.html5rocks.com/en/tutorials/appcache/beginner/

"...The manifest attribute should be included on every page of your web application that you want cached. ..."

**Comment by NekR** [comment] 2017-08-18 20:06
That's a way to do it. I don't get what you want. Something doesn't work for you or what?

**Comment by yaitskov** [comment] 2017-08-18 20:17
HtmlWebpackPlugin generates /dist/index.html. It's the only html file in the application.
There should be the binding to the manifest, but OfflinePlugin doesn't add the manifest attribute to <html> tag, instead the plugin generates another html file in subfolder /dist/appcache/ 

```
<!doctype html>
<html manifest="manifest.appcache"></html>
```

The file is almost empty. This is not a big problem for me to add the manifest attribute in my html template as a workaround, though I would like to know the right way to go.

By default I end up with 2 html files instead of 1 and both are not good.

**Comment by NekR** [comment] 2017-08-18 20:40
This is intended behaviour, you do not need to add manifest attribute in your html files. The right way to go is to accept how plugin works. If you don't like it, just don't use it.
